version: '3.8'
services:
  read-api:
    container_name: docker-read
    build: ./read
    ports:
      - '4000:4000'
    external_links:
      - mongo
  write-api:
    container_name: docker-write
    build: write/
    ports:
      - '3000:3000'
    external_links:
      - mongo
  db:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'